name: Algolia Search

on:
  schedule:
    - cron: '0 10 * * *'
  # TODO: Remove trigger from push event when search index scraper is fixed
  push:
    branches:
      - '7-fix-search'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Run Scraper
        run: |
          brew install jq
          docker run -e "APPLICATION_ID=${{ secrets.ALGOLIA_APP_ID }}" -e "API_KEY=${{ secrets.API_KEY }}" -e "CONFIG=$(cat ./config.json | jq -r tostring)" algolia/docsearch-scraper
