name: Algolia Search

on:
  schedule:
    - cron: '0 10 * * *'
  # TODO: Remove trigger from push event when search index scraper is fixed
  push:
    branches:
      - '7-fix-search'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Run Scraper
        run: |
          brew install jq
          docker run -e "APPLICATION_ID=${{ secrets.ALGOLIA_APP_ID }}" -e "API_KEY=${{ secrets.API_KEY }}" -e "CONFIG=$(cat ./config.json | jq -r tostring)" algolia/docsearch-scraper
